        SELECT RTRIM(XMLAGG(XMLELEMENT(x,T2.ORD_NO,CHR(35)) ORDER BY T2.ORD_NO).EXTRACT('//text()'),',') AS ORD_NOS
          FROM TR_DC_CONTENTS_LOG T1
             , TR_ORD_PRD T2
         WHERE T1.ORD_NO > TO_CHAR(SYSDATE - 10, 'YYYYMMDD')||'0000000'
           AND T1.ORD_NO = T2.ORD_NO
           AND T1.ORD_PRD_SEQ = T2.ORD_PRD_SEQ
           AND T2.ORD_PRD_STAT = '202'
