CREATE OR REPLACE FUNCTION FUNC_LONG_TO_CHAR ( 
      IN_TABLE_NAME    VARCHAR2
    , IN_COLUMN        VARCHAR2
    , IN_WHERE_COLUMN1 VARCHAR2
    , IN_VALUE1        VARCHAR2
    , IN_WHERE_COLUMN2 VARCHAR2
    , IN_VALUE2        VARCHAR2
    ) 
RETURN VARCHAR2 AS 
    TEMP_LONG     LONG;
    TEMP_VARCHAR2 VARCHAR2(32767);
    SQL_CUR       VARCHAR2(32767);
    SQL_CUR1      VARCHAR2(32767);
    SQL_CUR2      VARCHAR2(70);
BEGIN

    SQL_CUR1 := 'SELECT '||IN_COLUMN||' FROM '|| IN_TABLE_NAME||' WHERE '|| IN_WHERE_COLUMN1 || ' = ''' || IN_VALUE1 || '''';
    
    IF ( IN_WHERE_COLUMN2 IS NOT NULL AND IN_VALUE2 IS NOT NULL) THEN
        SQL_CUR2 := ' AND '|| IN_WHERE_COLUMN2 || ' = ''' || IN_VALUE2 || '''';
    ELSE
        SQL_CUR2 := NULL;
    END IF;

    SQL_CUR := SQL_CUR1 || SQL_CUR2;
    
    EXECUTE IMMEDIATE SQL_CUR INTO TEMP_LONG;

    TEMP_VARCHAR2 := SUBSTR(TEMP_LONG, 1, 4000);
    RETURN TEMP_VARCHAR2; 
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
