SET ECHO OFF
SET FEEDBACK OFF
SET LINES 170
SET PAGES 999
COL COLUMNS FORMAT A30 HEADING "Columns"
COL OWNER FORMAT A10 HEADING "Owner"
COL TABLE_NAME FORMAT A25 HEADING "Table|Name"
COL INDEX_NAME FORMAT A30 HEADING "Index|Name"
COL UQ FORMAT A2 HEADING "UQ"
COL INDEX_TYPE FORMAT A5 HEADING "Index|Type"
COL TABLESPACE_NAME FORMAT A10 HEADING "Tablespace|Name"
COL PCT_FREE FORMAT 9,999 HEADING "Pct|Free"
COL INI_TRANS FORMAT 9,999 HEADING "Init|Trans"
COL INITIAL_EXTENT FORMAT 9,999 HEADING "Initial|Extent(MB)"
COL NEXT_EXTENT FORMAT 9,999 HEADING "Next|Extent(MB)"
COL PARTITIONED FORMAT A4 HEADING "Is|Part"

 

ACCEPT OWNER CHAR PROMPT 'Enter value for owner: '
ACCEPT TABLE_NAME CHAR PROMPT 'Enter value for table_name: '

TTITLE 'Index Informations On &TABLE_NAME(s) for &OWNER'

SELECT OWNER, TABLE_NAME
     , INDEX_NAME
     , UQ, INDEX_TYPE
     , MAX(DECODE(COLUMN_POSITION, 1, COLUMN_NAME || DESCEND))
    || MAX(DECODE(COLUMN_POSITION, 2, NVL(', '||COLUMN_NAME || DESCEND,'')))
    || MAX(DECODE(COLUMN_POSITION, 3, NVL(', '||COLUMN_NAME || DESCEND,'')))
    || MAX(DECODE(COLUMN_POSITION, 4, NVL(', '||COLUMN_NAME || DESCEND,'')))
    || MAX(DECODE(COLUMN_POSITION, 5, NVL(', '||COLUMN_NAME || DESCEND,'')))
    || MAX(DECODE(COLUMN_POSITION, 6, NVL(', '||COLUMN_NAME || DESCEND,'')))
    || MAX(DECODE(COLUMN_POSITION, 7, NVL(', '||COLUMN_NAME || DESCEND,'')))
    || MAX(DECODE(COLUMN_POSITION, 8, NVL(', '||COLUMN_NAME || DESCEND,'')))
    || MAX(DECODE(COLUMN_POSITION, 9, NVL(', '||COLUMN_NAME || DESCEND,''))) AS COLUMNS
    , TABLESPACE_NAME, PCT_FREE, INI_TRANS
    , INITIAL_EXTENT/1024/1024 AS INITIAL_EXTENT
    , NEXT_EXTENT/1024/1024 AS NEXT_EXTENT
    , PARTITIONED
    , STATUS
  FROM (SELECT  A.OWNER, A.TABLE_NAME, A.INDEX_NAME
              , DECODE( A.INDEX_TYPE,'NORMAL','','FUNCTION-BASED NORMAL','FBI'
                                    ,'BITMAP','BIT','IOT - TOP','IOT',A.INDEX_TYPE) AS INDEX_TYPE
              , DECODE(A.UNIQUENESS,'UNIQUE','U') AS UQ
              , DECODE( E.COLUMN_POSITION, NULL, B.COLUMN_NAME
                                         , FUNC_LONG_TO_CHAR ( 'ALL_IND_EXPRESSIONS'
                                            , 'COLUMN_EXPRESSION'
                                            , 'INDEX_NAME'
                                            , A.INDEX_NAME
                                            , 'INDEX_OWNER'
                                            , A.OWNER )) AS COLUMN_NAME
              , DECODE(B.DESCEND,'DESC', ' DESC') AS DESCEND
              , A.STATUS, A.TABLESPACE_NAME, A.PCT_FREE, A.INI_TRANS, A.INITIAL_EXTENT
              , A.NEXT_EXTENT, A.PARTITIONED, B.COLUMN_POSITION
          FROM DBA_INDEXES A, DBA_IND_COLUMNS B, DBA_CONSTRAINTS D, ALL_IND_EXPRESSIONS E
         WHERE A.OWNER = UPPER('&OWNER')
           AND A.TABLE_NAME LIKE UPPER('&TABLE_NAME') || '%'
           AND A.INDEX_NAME      = B.INDEX_NAME
           AND A.TABLE_OWNER     = D.OWNER (+)
           AND A.INDEX_NAME      = D.CONSTRAINT_NAME (+)
           AND B.INDEX_OWNER     = E.INDEX_OWNER(+)
           AND B.INDEX_NAME      = E.INDEX_NAME (+)
           AND B.COLUMN_POSITION = E.COLUMN_POSITION(+))
GROUP BY OWNER, TABLE_NAME, INDEX_NAME, UQ, INDEX_TYPE, TABLESPACE_NAME, PCT_FREE
    , INI_TRANS, INITIAL_EXTENT, NEXT_EXTENT, PARTITIONED, STATUS
ORDER BY TABLE_NAME, UQ;
